# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple Craft Network
email: support@simplecraft.us
description: > # this means to ignore newlines until "baseurl:"
  Minecraft Plugins - Graphic Design - Web Design
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Simple-Craft.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: SCNServers
github_username:  Simple-Craft
facebook_username: SimpleCraftNetwork
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 812 N Columbia Blvd. Unit C15-588515
address_city: Portland
address_state: OR
address_zip: 97217

# Build settings
markdown: kramdown
